#install.packages('stringi')
#install.packages('stringi', repos = "http://cran.us.r-project.org")
library(stringi)
library(devtools)
library(roxygen2)
#devtools::install_github('r-lib/testthat')
library(testthat)
options(testthat.output_file = "tests/tests_output.xml")
devtools::test(reporter=JunitReporter)
